// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiTBEDwm5exld7Szs0EunjCo0KlQPVj4E',
    appId: '1:535275923261:web:0b55757c599da58c8d0754',
    messagingSenderId: '535275923261',
    projectId: 'teens-next-6c767',
    authDomain: 'teens-next-6c767.firebaseapp.com',
    storageBucket: 'teens-next-6c767.appspot.com',
    measurementId: 'G-EJ1W2C3DST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYK52PewzQbHi9_PQLYB_BgOFQFXswmhU',
    appId: '1:535275923261:android:11f71443e03849ad8d0754',
    messagingSenderId: '535275923261',
    projectId: 'teens-next-6c767',
    storageBucket: 'teens-next-6c767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCimT0uMZv9xmHbaOfrKCWVWpCymxLDj8Q',
    appId: '1:535275923261:ios:9e59c75396f59a008d0754',
    messagingSenderId: '535275923261',
    projectId: 'teens-next-6c767',
    storageBucket: 'teens-next-6c767.appspot.com',
    iosClientId: '535275923261-g60k5ah5tsurpdrnkmohe65lmtootmb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.teensNext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCimT0uMZv9xmHbaOfrKCWVWpCymxLDj8Q',
    appId: '1:535275923261:ios:368e4ef3fe9637d38d0754',
    messagingSenderId: '535275923261',
    projectId: 'teens-next-6c767',
    storageBucket: 'teens-next-6c767.appspot.com',
    iosClientId: '535275923261-7d1qmrdd3uhqmn19bq7qmaf0p55fp0mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.teensNext.RunnerTests',
  );
}
